### PR TITLE
Small fixes

### LINKED ISSUE #126: Feed error
Redirect the user to the login page when the feed data can not be retrieved because the cookie has been expired.

Possible fix: use the onError of the getFeed query to Redirect the user back to the login page.

### PR DESCRIPTION
**Pull request by mohammadalnajar**
# Description

- redirect the user to login if the session is expired
- capitalize user names

Fixes #126 #124 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

File: client/src/components/post/components/PostAuthorAction.jsx [hunk 1]
```diff
@@ -16,6 +18,11 @@ const PostAuthorAction = ({ id, userId, text, visibility, firstName }) => {
       // invalidate getFeedPosts query to refetch it
       queryClient.invalidateQueries('getFeedPosts');
     },
+    onError: (error) => {
```
Comment (Hani-AS) [inline client/src/components/post/components/PostAuthorAction.jsx:21]: This code snippet is repeated quite often. Create a function that accepts onError and navigate.

**Review by Hani-AS — COMMENTED** [review]
Added a comment. Another thing that I saw is that u have a navigate inside the alert component. Imo that component shouldn't not have such a functionality and should be kept as a stupid component. 

A simple alternative is to use a setTimeOut inside the feed component when there is an error. For example if there is an error then show that error for 3 sec and then navigate to /

Or something else that does the same.

File: client/src/components/post/components/PostAuthorAction.jsx (hunk 1 above)
Comment (mohammadalnajar) [reply client/src/components/post/components/PostAuthorAction.jsx:21]: done!
